### PR TITLE
Update progress.md

### PR DESCRIPTION
**Pull request by egelja**

### CODE REVIEW

**Comment by echavemann** [comment]
very wrong pls fix

**Comment by echavemann** [comment]
bruh if ur gonna do that just pull the head and fpush

**Comment by echavemann** [comment]
also can we fix the link on akash

**Comment by egelja** [comment]
just squash

**Comment by echavemann** [comment]
> just squash

no fix it

**Comment by echavemann** [comment]
ok whatever i will do it myself idk why a md file is too hard

**Pull request merged**
